config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    registrations: 'admin/registrations'
  }

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    root to: 'homes#top'
    resources :users,only: [:index, :show, :edit, :update]
    resources :animals, only: [:index, :show, :create, :edit, :destroy, :update]
  end

  root to: 'homes#top'
  get "/about" => "homes#about", as: "about"

  resources :animals, only: [:index, :show, :create, :edit, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :animal_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :create, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
  	get 'followings' => 'relationships#followings', as: 'followings'
  	get 'followers' => 'relationships#followers', as: 'followers'
  end

  get '/search' => 'searches#search'


end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/animal.rb
class Animal < ApplicationRecord
  belongs_to :user
  attachment :animal_image
  has_many :animal_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true

  validates :body, presence: true,
  length: {  maximum: 200}

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search_for(value,how)
    if how == 'perfect'
      Book.where(title: value)
    elsif how == 'forward'
      Book.where('title LIKE ?', value+'%')
    elsif how == 'backward'
      Book.where('title LIKE ?', '%'+value)
    else
      Book.where('title LIKE ?', '%'+value+'%')
    end
  end
end

app/models/animal_comment.rb
class AnimalComment < ApplicationRecord

  belongs_to :user
  belongs_to :animal
  validates :comment, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :animal
  validates_uniqueness_of :animal_id, scope: :user_id

end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :animals, dependent: :destroy
  has_many :animal_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :image

  validates :name, presence: true,
  length: { minimum: 2 , maximum: 20},
  uniqueness: true

  validates :introduction,
  length: {  maximum: 50}

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロー取得
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロワー取得

  has_many :followers, through: :reverse_of_relationships, source: :follower # 自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed # 自分をフォローしている人

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.search_for(value,how)
    if how == 'perfect'
      User.where(name: value)
    elsif how == 'forward'
      User.where('name LIKE ?', value+'%')
    elsif how == 'backward'
      User.where('name LIKE ?', '%'+value)
    else
      User.where('name LIKE ?', '%'+value+'%')
    end
  end
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @animals = Animal.all.page(params[:page]).per(10)
  end

  def destroy
    @animal = Animal.find(params[:id])
    @animal.destroy
    redirect_to admin_root_path
  end

end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def show
    @animal = Animal.find(params[:id])
    @user = @animal.user
    @animal_new = Animal.new
    @animal_comment = AnimalComment.new
  end

  def edit
    @animal = Animal.find(params[:id])
    flash[:notice2] = "You have updated animal successfully."
    if @animal.user == current_user
      render "edit"
    else
      redirect_to animals_path
    end
  end

  def update
    @animal = Animal.find(params[:id])
    if@animal.update(animal_params)
    redirect_to animal_path
    else
    render :edit
    end
  end

  def create
    @animal = Animal.new(animal_params)
    @animal.user_id = current_user.id
    if @animal.save
      flash[:notice] = "You have created animal successfully."
      redirect_to animal_path(@animal)
    else
      @Animals = Animal.all
      @user = current_user
      render :index
    end
  end

  def index
    @animals = Animal.all
    @animal = Animal.new
    @user = current_user
  end

  def destroy
    @animal = Animal.find(params[:id])
    @animal.destroy
    if @animal.user == current_user
      redirect_to animals_path
    else
    end
  end

  private

  def animal_params
    params.require(:animal).permit(:title, :body, :animal_image)
  end

  def ensure_correct_user
    @animal = Animal.find(params[:id])
    unless @animal.user == current_user
      redirect_to animals_path
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!

  def create
    @animal = Animal.find(params[:animal_id])
    favorite = @animal.favorites.new(user_id: current_user.id)
    favorite.save
  end

  def destroy
    @animal = Animal.find(params[:animal_id])
    favorite = @animal.favorites.find_by(user_id: current_user.id)
    favorite.destroy
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
  end
  
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @model = params[:model]
    @value = params[:value]
    @how = params[:how]
    if @model == 'user'
        @records = User.search_for(@value,@how)
    else
        @records = Animal.search_for(@value,@how)
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @animals = @user.animals
    @animal = Animal.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    redirect_to user_path(@user.id)
    flash[:notice] = "You have updated user successfully."
    else
      render :edit
    end
  end

  def create
    @user = User.new
    redirect_to animals_path
  end

  def index
    @Animals = Animal.all
    @animal = Animal.new
    @user = current_user
    @users = User.all
  end

  private

  def user_params
    params.require(:user).permit(:name, :image,:introduction,:title,:email)
  end

  def correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user.id)
    end
  end

end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/animal_comments_helper.rb
module AnimalCommentsHelper
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/homes/top.html.erb
<main>
  <div class="container">
      <div class="pt-5">
        <h3><span style="background-color:#dcdcdc">投稿一覧</span></h3>
          <table class="table">
            <thead>
              <tr>
                <th>名前</th>
                <th>User</th>
                <th>画像</th>
                <th>タイトル</th>
                <th>内容</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @animals.each do |animal| %>
                <tr id="animal_<%= animal.id %>">
                  <td><%= animal.user.name %></td>
                  <td><%= link_to admin_user_path(animal.user.id) do %>
                    <%= attachment_image_tag(animal.user, :image, size:"40x40", format: 'jpeg', fallback: "no_image.jpg") %>
                    <% end %>
                  </td>
                  <td><%= attachment_image_tag(animal, :animal_image, size:"40x40", format: 'jpeg', fallback: "no_image.jpg") %></td>
                  <td><%= animal.title %></td>
                  <td><%= animal.body %></td>
                  <td><%= link_to '削除', admin_animal_path(animal), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_animal_#{animal.id}"%></td>
                </tr>
              <% end %>
            </tbody>
          </table>

          <%= paginate @animals %>
      </div>
    </div>
  </main>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">全国の動物好きが集まる場所！</br>
    それがここ<strong>Animals</strong>です！</h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
        <div class="row">
            <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
                <h1>welcome to <i class="fas fa-paw"></i><strong>Animals</strong>  !!</h1>
                <p>動物好きが集まるAnimalsへようこそ！</p>
                <p>ここでは動物の知って欲しい所や好きな所</p>
                <p>飼っているペットの可愛い所や自慢したい所など</p>
                <p>全国の動物が好きな人達と共有出来るサイトです！</p>
                <div class="btn-wrapper col-10 mx-auto">
                    <div class="row">
                      <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
                    </div>
                    <div class="row">
                      <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign Up</a>
                    </div>
                </div>
            </div>
        </div>
</div>