config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    registrations: 'admin/registrations'
  }

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    root to: 'homes#top'
    resources :users,only: [:index, :show, :edit, :update]
    resources :animals, only: [:index, :show, :create, :edit, :destroy, :update]
  end

  root to: 'homes#top'
  get "/about" => "homes#about", as: "about"

  resources :animals, only: [:index, :show, :create, :edit, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :animal_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :create, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
  	get 'followings' => 'relationships#followings', as: 'followings'
  	get 'followers' => 'relationships#followers', as: 'followers'
  end

  get '/search' => 'searches#search'


end

app/models/animal.rb
class Animal < ApplicationRecord
  belongs_to :user
  attachment :animal_image
  has_many :animal_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true

  validates :body, presence: true,
  length: {  maximum: 200}

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search_for(value,how)
    if how == 'perfect'
      Book.where(title: value)
    elsif how == 'forward'
      Book.where('title LIKE ?', value+'%')
    elsif how == 'backward'
      Book.where('title LIKE ?', '%'+value)
    else
      Book.where('title LIKE ?', '%'+value+'%')
    end
  end
end

app/controllers/admin/animals_controller.rb
class Admin::AnimalsController < ApplicationController
  before_action :authenticate_admin!

  def destroy
    @animal = Animal.find(params[:id])
    @animal.destroy
    redirect_to admin_root_path
  end

end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def show
    @animal = Animal.find(params[:id])
    @user = @animal.user
    @animal_new = Animal.new
    @animal_comment = AnimalComment.new
  end

  def edit
    @animal = Animal.find(params[:id])
    flash[:notice2] = "You have updated animal successfully."
    if @animal.user == current_user
      render "edit"
    else
      redirect_to animals_path
    end
  end

  def update
    @animal = Animal.find(params[:id])
    if@animal.update(animal_params)
    redirect_to animal_path
    else
    render :edit
    end
  end

  def create
    @animal = Animal.new(animal_params)
    @animal.user_id = current_user.id
    if @animal.save
      flash[:notice] = "You have created animal successfully."
      redirect_to animal_path(@animal)
    else
      @Animals = Animal.all
      @user = current_user
      render :index
    end
  end

  def index
    @animals = Animal.all
    @animal = Animal.new
    @user = current_user
  end

  def destroy
    @animal = Animal.find(params[:id])
    @animal.destroy
    if @animal.user == current_user
      redirect_to animals_path
    else
    end
  end

  private

  def animal_params
    params.require(:animal).permit(:title, :body, :animal_image)
  end

  def ensure_correct_user
    @animal = Animal.find(params[:id])
    unless @animal.user == current_user
      redirect_to animals_path
    end
  end
end

app/helpers/admin/animals_helper.rb
module Admin::AnimalsHelper
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/views/animals/_comment.html.erb
<table>
  <% @animal.animal_comments.each do |animal_comment| %>
    <% animal_comment_user = animal_comment.user %>
    <tr>
    	<td>
    		<%= link_to user_path(animal_comment_user), class: "user_#{animal_comment_user.id}" do %>
      		<%= attachment_image_tag animal_comment_user, :image, :fill, 50, 50, fallback: "no_image.jpg", size: "50x50" %><br>
      		<%= animal_comment_user.name %>
    		<% end %>
    	</td>
    	<td><%= animal_comment.comment %></td>
    	<% if current_user == animal_comment_user %>
      	<td><%= link_to 'Destroy', animal_animal_comment_path(animal_comment.animal_id, animal_comment.id), class: 'btn-sm btn-danger', method: :delete %></td>
    	<% end %>
    </tr>
  <% end %>
</table>
<%= form_with model:[@animal,@animal_comment], local: true do |f| %>
  <%= f.text_area :comment, size:"90x5" %><br>
  <%= f.submit '送信'%>
<% end %>

app/views/animals/_form.html.erb
<%= form_with model:animal,local:true do |f| %>


  <div class="form-group">
    <%= f.label :画像 %>
    <%= f.file_field :animal_image, class: "image" %>
  </div>

  <div class="form-group">
    <%= f.label :タイトル %>
    <%= f.text_field :title, class: 'form-control animal_title' %>
  </div>
  <div class="form-group">
    <%= f.label :内容 %>
    <%= f.text_area :body, class: 'form-control animal_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/animals/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th>ユーザー</th>
      <th>画像</th>
      <th>タイトル</th>
      <th>内容</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% animals.each do |animal| %>
      <tr id="animal_<%= animal.id %>">
        <td><%= link_to user_path(animal.user) do %>
          <%= attachment_image_tag(animal.user, :image, size:"40x40", format: 'jpeg', fallback: "no_image.jpg") %>
          <% end %>
        </td>
        <td><%= attachment_image_tag(animal, :animal_image, size:"40x40", format: 'jpeg', fallback: "no_image.jpg") %></td>
        <td><%= link_to animal.title, animal_path(animal), class: "animal_#{animal.id}" %></td>
        <td><%= animal.body %></td>
        <td class="favorite-btn"><%= render "favorites/favorite-btn", animal: animal %></td>
        <td>コメント数: <%= animal.animal_comments.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/animals/edit.html.erb
<% if @animal.errors.any? %>
  <div id="error_explanation">
    <h3><%= @animal.errors.count %>errors prohibited this obj from being saved:</h3><br>
    <ul>
      <% @animal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
       <h2>編集ページ</h2>

        <%= render 'form', animal: @animal %>
        <%= link_to "詳細へ",animal_path(@animal.id) %>
        |
        <%= link_to "戻る",animals_path %>
      </div>
    </div>
  </div>

app/views/animals/index.html.erb
<% if @animal.errors.any? %>
    <div id="error_explanation">
        <h3><%= @animal.errors.count %>errors prohibited this obj from being saved:</h3><br>
        <ul>
          <% @animal.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
    </div>
<% end %>

<div class="container px-5 px-sm-0">
    <div class="row">
        <div class="col-md-3">
            <h2>プロフィール</h2>
            <%= render 'users/info', user: current_user %>
            <h2>New animal</h2>
            <%= render 'form', animal: @animal %>
        </div>
        <div class="col-md-8 offset-md-1">
            <h2>Animals</h2>
            <%= render 'index', animals: @animals%>
        </div>
    </div>
</div>

app/views/animals/show.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>
<% if flash[:notice2] %>
  <p><%= flash[:notice2] %></p>
<% end %>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>プロフィール</h2>
      <%= render 'users/info', user: @animal.user %>
      <h2>New animal</h2>
      <%= render 'form', animal: Animal.new %>
    </div>
      <div class="col-md-8 offset-md-1">
       <h2>Animal 詳細</h2>
        <table class="table">
              <tr id="animal_<%= @animal.id %>">
                <td><%= link_to user_path(@animal.user) do %>
                  <%= attachment_image_tag(@animal.user, :image, size:"40x40", format: 'jpeg', fallback: "no_image.jpg") %><br>
                  <%= @animal.user.name %>
                  <% end %>
                </td>
                <td><%= attachment_image_tag(@animal, :animal_image, size:"40x40", fallback: "no_image.jpg") %></td>
                <td><%= link_to @animal.title, animal_path(@animal) %></td>
                <td><%= @animal.body %></td>
                <td class="favorite-btn"><%= render "favorites/favorite-btn", animal: @animal %></td>
                <td class="comments-count">コメント数: <%= @animal.animal_comments.count %></td>
                <% if @user.id == current_user.id %>
                  <td><%= link_to '編集', edit_animal_path(@animal), class: "btn btn-sm btn-success edit_animal_#{@animal.id}" %></td>
                  <td><%= link_to '削除', animal_path(@animal), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_animal_#{@animal.id}"%></td>
                <% end %>
              </tr>
        </table>
        <table class="animal_comments">
          <%= render 'animal_comments/index', animal: @animal %>
        </table>
        <%= form_with model:[@animal,@animal_comment], remote: true do |f| %>
          <%= f.text_area :comment, size:"90x5" %><br>
          <%= f.submit '送信'%>
        <% end %>
      </div>
    </div>
</div>