config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    registrations: 'admin/registrations'
  }

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    root to: 'homes#top'
    resources :users,only: [:index, :show, :edit, :update]
    resources :animals, only: [:index, :show, :create, :edit, :destroy, :update]
  end

  root to: 'homes#top'
  get "/about" => "homes#about", as: "about"

  resources :animals, only: [:index, :show, :create, :edit, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :animal_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :create, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
  	get 'followings' => 'relationships#followings', as: 'followings'
  	get 'followers' => 'relationships#followers', as: 'followers'
  end

  get '/search' => 'searches#search'


end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/animal.rb
class Animal < ApplicationRecord
  belongs_to :user
  attachment :animal_image
  has_many :animal_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true

  validates :body, presence: true,
  length: {  maximum: 200}

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search_for(value,how)
    if how == 'perfect'
      Book.where(title: value)
    elsif how == 'forward'
      Book.where('title LIKE ?', value+'%')
    elsif how == 'backward'
      Book.where('title LIKE ?', '%'+value)
    else
      Book.where('title LIKE ?', '%'+value+'%')
    end
  end
end

app/models/animal_comment.rb
class AnimalComment < ApplicationRecord

  belongs_to :user
  belongs_to :animal
  validates :comment, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :animal
  validates_uniqueness_of :animal_id, scope: :user_id

end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :animals, dependent: :destroy
  has_many :animal_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :image

  validates :name, presence: true,
  length: { minimum: 2 , maximum: 20},
  uniqueness: true

  validates :introduction,
  length: {  maximum: 50}

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロー取得
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロワー取得

  has_many :followers, through: :reverse_of_relationships, source: :follower # 自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed # 自分をフォローしている人

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.search_for(value,how)
    if how == 'perfect'
      User.where(name: value)
    elsif how == 'forward'
      User.where('name LIKE ?', value+'%')
    elsif how == 'backward'
      User.where('name LIKE ?', '%'+value)
    else
      User.where('name LIKE ?', '%'+value+'%')
    end
  end
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def show
    @animal = Animal.find(params[:id])
    @user = @animal.user
    @animal_new = Animal.new
    @animal_comment = AnimalComment.new
  end

  def edit
    @animal = Animal.find(params[:id])
    flash[:notice2] = "You have updated animal successfully."
    if @animal.user == current_user
      render "edit"
    else
      redirect_to animals_path
    end
  end

  def update
    @animal = Animal.find(params[:id])
    if@animal.update(animal_params)
    redirect_to animal_path
    else
    render :edit
    end
  end

  def create
    @animal = Animal.new(animal_params)
    @animal.user_id = current_user.id
    if @animal.save
      flash[:notice] = "You have created animal successfully."
      redirect_to animal_path(@animal)
    else
      @Animals = Animal.all
      @user = current_user
      render :index
    end
  end

  def index
    @animals = Animal.all
    @animal = Animal.new
    @user = current_user
  end

  def destroy
    @animal = Animal.find(params[:id])
    @animal.destroy
    if @animal.user == current_user
      redirect_to animals_path
    else
    end
  end

  private

  def animal_params
    params.require(:animal).permit(:title, :body, :animal_image)
  end

  def ensure_correct_user
    @animal = Animal.find(params[:id])
    unless @animal.user == current_user
      redirect_to animals_path
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @animals = @user.animals
    @animal = Animal.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    redirect_to user_path(@user.id)
    flash[:notice] = "You have updated user successfully."
    else
      render :edit
    end
  end

  def create
    @user = User.new
    redirect_to animals_path
  end

  def index
    @Animals = Animal.all
    @animal = Animal.new
    @user = current_user
    @users = User.all
  end

  private

  def user_params
    params.require(:user).permit(:name, :image,:introduction,:title,:email)
  end

  def correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user.id)
    end
  end

end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/animal_comments_helper.rb
module AnimalCommentsHelper
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Animals</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" >
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/9c1df0e710.js" crossorigin="anonymous"></script>
  </head>
  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm bg-dark text-white">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <div class="navbar-brand ">
            <%= link_to ' Animals', root_path, class: 'fas fa-hippo nav-link text-white' %>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item"><%= link_to ' Home' , user_path(current_user.id), class: 'fas fa-dog nav-link text-white', method: :get %></li>
              <li class="nav-item"><%= link_to ' Users' , users_path, class: 'fas fa-users nav-link text-white', method: :get %></li>
              <li class="nav-item"><%= link_to ' Animals' , animals_path, class: 'fas fa-cat nav-link text-white', method: :get %></li>
              <li class="nav-item"><%= link_to ' logout' , destroy_user_session_path, method: :delete, class: 'fas fa-sign-out-alt nav-link text-white' %></li>

            <% elsif admin_signed_in? %>
              <li class="nav-item"><%= link_to '会員一覧', admin_users_path,class: "btn btn-outline-dark text-white" %></li>
              <li class="nav-item"><%= link_to '投稿一覧', admin_root_path,class: "btn btn-outline-dark text-white" %></li>
              <li class="nav-item"><%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: "btn btn-outline-dark text-white" %></li>

            <% else %>
              <li class="nav-item"><%= link_to ' Home' , root_path, class: 'fas fa-dog nav-link text-white', method: :get %></li>
              <li class="nav-item"><%= link_to ' About' , about_path, class: 'fas fa-dove nav-link text-white', method: :get %></li>
              <li class="nav-item"><%= link_to ' Sign up' , new_user_registration_path, class: 'fas fa-user-plus nav-link text-white', method: :get %></li>
              <li class="nav-item"><%= link_to ' login' , new_user_session_path, class: 'fas fa-sign-in-alt nav-link text-white', method: :get %></li>
            <% end %>

            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <div class="col-xs-6 col-xs-offset-3 text-center" style="margin-top: 5px;">
        <% if user_signed_in? %>
          <%= form_with url:search_path, method: :get, local: true do |f| %>
            <%= f.text_field :value %>
            <%= f.select :model, options_for_select({ "User" => "user", "Animal" => "animal" }) %>
            <%= f.select :how, options_for_select({ "完全一致" => "perfect", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partial"  }) %>
            <%= f.submit :"検索" %>
          <% end %>
        <% end %>
      </div>
      <%= yield %>
    </main>
  </body>

</html>